### PR TITLE
Upgrade swagger-codegen to v2.4.10

### PR DESCRIPTION
**Pull request by chenrui333**
relates to https://github.com/meetup/rules_openapi/pull/24

### CODE REVIEW

**Comment by chenrui333** [comment]
`Error: Could not find or load main class io.swagger.codegen.SwaggerCodegen`

**Comment by softprops** [comment]
> Error: Could not find or load main class io.swagger.codegen.SwaggerCodegen

Possibly a breaking change?

**Comment by chenrui333** [comment]
I doubt it is breaking change, but let do one minor version at a time.

**Comment by chenrui333** [comment]
Looks like v2.3.1 bump works fine.

**Pull request closed without merging**
